// UI Components
import Header from "@/components/Header";

// Fonts
import { Barlow } from "next/font/google";

// Styles
import "./globals.css";

// Types
import type { Metadata } from "next";

const font = Barlow({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        <div className="pt-24 max-md:pt-16">{children}</div>
      </body>
    </html>
  );
}
